### ISSUE TITLE
Minimum drain-time check is incorrect

### ISSUE THREAD

**Issue by arjunpdhaliwal** [Naxesss/MapsetVerifier#10]
On this map: https://osu.ppy.sh/beatmapsets/1216983#osu/2532174

Verifier reports the drain time as being ~4:13, when in reality it's something like 4:17. I think it's not counting the spinner at 01:23:731 (1) - somehow.

**Comment by Naxesss** [comment]
seems to be related to https://github.com/Naxesss/MapsetParser/blob/master/objects/Beatmap.cs#L401 getting the object before the spinner instead of the spinner itself, should be an easy fix
