### ISSUE TITLE
How to install on linux

### ISSUE THREAD

**Issue by seriaati** [Naxesss/MapsetVerifier#13]
I'm new to linux and is using ubuntu 20.04 LTS
I searched on google about installing tar.gz files
But I followed the tutorial and it gives me an error of like "config, no such directory" or "INSTALL, no such file" etc

**Comment by Kyuunex** [comment]
on ubuntu (default flavor), just extract the tar.gz archive, open the terminal in the newly extracted folder, and type `./mapsetverifier`

**Comment by seriaati** [comment]
It works, thank you.
