### ISSUE TITLE
Error testing for omitted barline consistency with inconsistent timing

### ISSUE THREAD

**Issue by Alchyr** [Naxesss/MapsetVerifier#19]
![image](https://user-images.githubusercontent.com/39511935/145245093-c68f7350-1671-4c36-82e3-99f0aeaedcad.png)

One difficulty has slightly offset timing to the others, as I was in the process of applying mods and haven't updated one of the difficulties as it's a gd and adjusting offset makes applying mods inconvenient.

https://drive.google.com/file/d/1EjkkYaCMPXD6FEmERAVJeeIAMWh4SSqu/view?usp=sharing
Exported .osz of the mapset in question

**Comment by Naxesss** [comment]
Found and solved the issue - seems that I forgot to account for the case of lines not being consistent. The check tried to compare two lines at the same time between difficulties, but one difficulty was missing that line, hence the exception you see.

Good catch! Will push with the next update, whenever that happens.
