### ISSUE TITLE
Program always says backend error when trying to load a map

### ISSUE THREAD

**Issue by ffrunk** [Naxesss/MapsetVerifier#27]
![image](https://user-images.githubusercontent.com/87246981/185406506-015ead89-fb55-4396-ae2e-f64eff5e4ea0.png)
![image](https://user-images.githubusercontent.com/87246981/185406603-672523ae-d1bc-420a-9fd1-3065aa31677a.png)
No idea what this means, I tried restarting computer & program but it didn't work (Win10)
It never loads the map, infinite load

**Comment by iAimFoxZ** [comment]
i'm getting the same problem

**Comment by ffrunk** [comment]
with naxess help i got it fixed, it was a crypto miner called salad interfering with mapset verifier, close it if you are having this exact problem before running mv :)

**Comment by Naxesss** [comment]
For future reference, you can check what's taking the port MV wants like this on windows:
![](https://cdn.discordapp.com/attachments/1010891871784018050/1010904014948409355/unknown.png)
`netstat -ano | findstr :5000` (From this you can see the PIDs on the right)
`tasklist | findstr <PID>` (This tells you what the process with that PID is called)
`taskkill /PID <PID> /F` (This kills the process with the given PID)
