### ISSUE TITLE
genre and language bug

### ISSUE THREAD

**Issue by Amazed-101** [Naxesss/MapsetVerifier#28]
bug on genre and languages. after refreshing and updating the beatmap and restarting the app, it wont see that it has genre and languages set.

![image](https://user-images.githubusercontent.com/111684567/185787210-04bba4a7-ae51-4ab5-ba1e-cb93b2bc5ff7.png)

**Comment by Naxesss** [comment]
If you don't put "electronic" and "english" in the **tags**, then they won't be searchable in-game. That's why it's warning you that they are missing.
