### ISSUE TITLE
Value was either too large or too small for a UInt64

### ISSUE THREAD

**Issue by Limeony** [Naxesss/MapsetVerifier#34]
![image](https://user-images.githubusercontent.com/8150808/226084225-afb0a58d-d5a8-4d02-8797-25c7177157e6.png)
happens only with one map
this error was not present before

**Comment by Morilli** [comment]
This happen when the `BeatmapID` is set to a negative value, like `-1`. However this should still be fixed as it appears osu treats beatmapid and beatmapsetid as `int` internally, so parsing as `ulong` seems incorrect.

**Comment by Limeony** [comment]
> This happen when the `BeatmapID` is set to a negative value, like `-1`. However this should still be fixed as it appears osu treats beatmapid and beatmapsetid as `int` internally, so parsing as `ulong` seems incorrect.

Better late than never, thanks.
